<?php

namespace Hopjob\FrontBundle\Repository;

/**
 * DemandeServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
