<?php

namespace Hopjob\FrontBundle\Repository;

/**
 * SousDomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousDomaineRepository extends \Doctrine\ORM\EntityRepository
{
}
