<?php

namespace Hopjob\FrontBundle\Repository;

/**
 * StatUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatUserRepository extends \Doctrine\ORM\EntityRepository
{
}
