<?php

namespace Hopjob\FrontBundle\Repository;

/**
 * TypeVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
