<?php

namespace Hopjob\FrontBundle\Repository;

/**
 * TypeDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
