app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }

pdf:
    path:     /pdf
    defaults: { _controller: AppBundle:Default:pdf }