admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"