app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }

pdf:
    path:     /pdf
    defaults: { _controller: AppBundle:Default:pdf }


admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }


messagerie:
    path:     /messagerie
    defaults: { _controller: AppBundle:Admin:messagerie }

code:
    path:     /code
    defaults: { _controller: AppBundle:Admin:code }


documents:
    path:     /documents
    defaults: { _controller: AppBundle:Admin:documents }