admin:
    path:     /
    defaults: { _controller: AdminBundle:Default:admin }

messagerie:
    path:     /messagerie
    defaults: { _controller: AdminBundle:Default:messagerie }

message:
    path:     /message/{id}
    defaults: { _controller: AdminBundle:Default:message }

code:
    path:     /code
    defaults: { _controller: AdminBundle:Default:code }

avis:
    path:     /avis
    defaults: { _controller: AdminBundle:Default:avis }

notation:
    path:     /notation/{id}
    defaults: { _controller: AdminBundle:Default:notation }

documents:
    path:     /documents
    defaults: { _controller: AdminBundle:Default:documents }