index:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Default:contact }

annonces:
    path:     /annonces
    defaults: { _controller: FrontBundle:Default:annonces }
    options:
        expose: true

pdf:
    path:     /pdf
    defaults: { _controller: FrontBundle:Default:pdf }

domaines:
    path:     /domaines/{domaines}
    defaults: { _controller: FrontBundle:Annonce:domaines }

sousdomaines:
    path:     /domaines/{domaines}/{sousdomaines}
    defaults: { _controller: FrontBundle:Annonce:sousdomaines }

createannonce:
    path:     /domaines/{domaine}/{sousdomaines}/createannonce/{activite}
    defaults: { _controller: FrontBundle:Annonce:createannonce }

detail_annonce:
    path:     /annonces/detail_annonce/{id}
    defaults: { _controller: FrontBundle:Default:detailannonce }

souscription:
    path:     /souscription
    defaults: { _controller: FrontBundle:Souscription:index }

paiement:
    path:     /paiement
    defaults: { _controller: FrontBundle:Souscription:paiement }


profil:
    path:     /user/{id}
    defaults: { _controller: FrontBundle:Utilisateur:Profil }

parametres:
    path:     /parametres
    defaults: { _controller: FrontBundle:Utilisateur:Parametres }